### ISSUE TITLE
Use openssl-x509 -serial

### ISSUE THREAD

**Issue by Sp1l** [hannob/lecaa#5]
Probably easier to use `openssl x509 -serial`, save some pipes...

**Comment by hannob** [comment]
I had another patch already for this and it broke things. -serial outputs in uppercase, so I'd have to have another conversion step for lowercase and that would eliminate every simplification advantage it would bring us.

**Comment by Sp1l** [comment]
Sorry for the noise! Hadn't dug deep enough...

Luckily I keep a Certificate Observatory where I have all the serials and various fingerprints at hand, easy checking...
