### ISSUE TITLE
Invalid parallel instructions in README: parallel: Error: Cannot open input file `<insert hostname>': No such file or directory.

### ISSUE THREAD

**Issue by solbu** [hannob/lecaa#6]
The parallel instruction is invalid. The command switch «-a» expects the input to be from a file named what the hostname is.
I have been experimenting a little on two diferent distro versions (I run Mageia Linux), and I get the exact same output.

`parallel -a my-hostname1 my-hostname2 my-hostname3 -j 30 --timeout 10 ./lecaa
parallel: Error: Cannot open input file `my-hostname1': No such file or directory.`

This command however works just fine.
`(echo my-hostname1; echo my-hostname2; echo my-hostname3) |parallel ./lecaa`

**Comment by hannob** [comment]
that's how I mean it, I'd assume most people have their affected hosts in some kind of file. I'll try to make that clearer
